### ISSUE TITLE
Bug: 希望docker镜像提供ubuntu版本，因为新版的node18及以上版本依赖新的gcc glibc库，而centos7 已经不再升级库版本

### ISSUE THREAD

**Issue by leochen-g** [openspug/spug#612]
Spug 版本:

## 问题重现步骤

1. 使用最新版docker镜像部署，进入容器安装node18版本
2.出现lib库报错

## 报错/问题截图
<img width="455" alt="image" src="https://github.com/openspug/spug/assets/20028566/f91d6da3-87f1-472e-a88d-62a177f491fa">

## 期望的结果

希望官方能够提供ubuntu版本的镜像提供部署，因为现在大部分的node项目都是基于node18了，降版本去编译不是一个好的方式

**Comment by leochen-g** [comment]
自己构建了一个基于ubuntu的镜像，可以解决node 18 的问题。
以下是docker-compose 文件，有需要的可以自取即可
```
version: "3.3"
services:
  db:
    image: mariadb:10.8
    container_name: spug-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/spug/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=spug
      - MYSQL_USER=spug
      - MYSQL_PASSWORD=spug.cc
      - MYSQL_ROOT_PASSWORD=spug.cc
  spug:
    image: aibotk/ubuntu-spug-service
    container_name: spug
    privileged: true
    restart: always
    volumes:
      - ./data/spug/service:/data/spug
      - ./data/spug/repos:/data/repos
    ports:
      # 如果80端口被占用可替换为其他端口，例如: - "8000:80"
      - "8000:80"
    environment:
      - SPUG_DOCKER_VERSION=v3.2.7
      - MYSQL_DATABASE=spug
      - MYSQL_USER=spug
      - MYSQL_PASSWORD=spug.cc
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db

```
